/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restauranterandom.swing;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import restauranterandom.entity.Restaurante;
import restauranterandom.util.PopulaRestaurante;

/**
 *
 * @author hersonn
 */
public class TelaInicial extends javax.swing.JFrame {

    private DefaultListModel lista = new DefaultListModel();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
        populaListaComObjetos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollRestaurante = new javax.swing.JScrollPane();
        jListaRestaurante = new javax.swing.JList<>();
        labelRestaurante = new javax.swing.JLabel();
        labelInserirRestaurante = new javax.swing.JLabel();
        txtNomeRestaurante = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonInserirRestaurante = new javax.swing.JButton();
        jButtonSortearRestaurante = new javax.swing.JButton();
        jButtonRemoverRestaurante = new javax.swing.JButton();
        jLabelResultadoRandom = new javax.swing.JLabel();
        jLabelResultadoGerado = new javax.swing.JLabel();
        jButtonLimparLista = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante Random");
        setAlwaysOnTop(true);

        jListaRestaurante.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListaRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaRestauranteMouseClicked(evt);
            }
        });
        jScrollRestaurante.setViewportView(jListaRestaurante);

        labelRestaurante.setText("Lista de Restaurantes");

        labelInserirRestaurante.setText("Inserir Restaurante");

        txtNomeRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRestauranteActionPerformed(evt);
            }
        });

        jButtonInserirRestaurante.setText("Inserir");
        jButtonInserirRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirRestauranteActionPerformed(evt);
            }
        });

        jButtonSortearRestaurante.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSortearRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restauranterandom/icon/homer1.jpg"))); // NOI18N
        jButtonSortearRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSortearRestauranteActionPerformed(evt);
            }
        });

        jButtonRemoverRestaurante.setText("Remover");
        jButtonRemoverRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverRestauranteActionPerformed(evt);
            }
        });

        jLabelResultadoRandom.setText("Resultado: ");

        jButtonLimparLista.setText("Limpar Lista");
        jButtonLimparLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparListaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRestaurante, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelInserirRestaurante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelResultadoRandom)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelResultadoGerado)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jButtonSortearRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInserirRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemoverRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimparLista)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(labelRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(labelInserirRestaurante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemoverRestaurante)
                            .addComponent(jButtonInserirRestaurante)
                            .addComponent(jButtonLimparLista))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSortearRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResultadoRandom)
                            .addComponent(jLabelResultadoGerado))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRestauranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRestauranteActionPerformed

    private void jButtonInserirRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirRestauranteActionPerformed
        String nomeRestaurante = txtNomeRestaurante.getText();
        if (txtNomeRestaurante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira um nome de restaurante"
                    + " para adicionar na lista!");
        } else if (jButtonInserirRestaurante.getText().equals("Inserir")) {
            Restaurante restaurante = new Restaurante();
            restaurante.setId(lista.getSize() + 1);
            restaurante.setNome(nomeRestaurante);
            lista.addElement(restaurante);
            jListaRestaurante.setModel(lista);
            JOptionPane.showMessageDialog(rootPane, "O restaurante foi inserido!");

        } else {
            Restaurante r = (Restaurante) lista.getElementAt(jListaRestaurante.getSelectedIndex());
            r.setNome(nomeRestaurante);
            lista.setElementAt(r, jListaRestaurante.getSelectedIndex());
            txtNomeRestaurante.setText(r.getNome());
            jButtonInserirRestaurante.setText("Inserir");
            JOptionPane.showMessageDialog(rootPane, "O restaurante foi alterado!");
        }
        txtNomeRestaurante.setText(new String());
    }//GEN-LAST:event_jButtonInserirRestauranteActionPerformed

    private void jButtonRemoverRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverRestauranteActionPerformed
        if (txtNomeRestaurante.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um restaurante para"
                    + " executar esta ação!");
        } else {
            lista.removeElementAt(jListaRestaurante.getSelectedIndex());
            txtNomeRestaurante.setText(new String());
            jButtonInserirRestaurante.setText("Inserir");
            JOptionPane.showMessageDialog(rootPane, "O restaurante foi removido!!");
            jLabelResultadoGerado.setText(new String());
        }
    }//GEN-LAST:event_jButtonRemoverRestauranteActionPerformed

    private void jListaRestauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaRestauranteMouseClicked
        Restaurante r = (Restaurante) lista.getElementAt(jListaRestaurante.getSelectedIndex());
        txtNomeRestaurante.setText(r.getNome());
        jButtonInserirRestaurante.setText("Alterar");
    }//GEN-LAST:event_jListaRestauranteMouseClicked

    private void jButtonSortearRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSortearRestauranteActionPerformed
        gerarResultadoRandom();
    }//GEN-LAST:event_jButtonSortearRestauranteActionPerformed

    private void jButtonLimparListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparListaActionPerformed
        if (lista.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Não há restaurantes na lista!");
        } else {
            lista.clear();
            JOptionPane.showMessageDialog(rootPane, "A lista de restaurantes foi limpa!!");
            jLabelResultadoGerado.setText(new String());
        }
    }//GEN-LAST:event_jButtonLimparListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInserirRestaurante;
    private javax.swing.JButton jButtonLimparLista;
    private javax.swing.JButton jButtonRemoverRestaurante;
    private javax.swing.JButton jButtonSortearRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelResultadoGerado;
    private javax.swing.JLabel jLabelResultadoRandom;
    private javax.swing.JList<String> jListaRestaurante;
    private javax.swing.JScrollPane jScrollRestaurante;
    private javax.swing.JLabel labelInserirRestaurante;
    private javax.swing.JLabel labelRestaurante;
    private javax.swing.JTextField txtNomeRestaurante;
    // End of variables declaration//GEN-END:variables

    public void populaListaComObjetos() {
        PopulaRestaurante popular = new PopulaRestaurante();
        List<Restaurante> listaRestaurante = new ArrayList<>();
        listaRestaurante = popular.popularRestaurantes();

        for (int i = 0; i < listaRestaurante.size(); i++) {
            lista.addElement(listaRestaurante.get(i));
        }

        jListaRestaurante.setModel(lista);
    }

    public void gerarResultadoRandom() {
        double random = Math.random() * lista.getSize();
        int valor = (int) random;
        jLabelResultadoGerado.setText(lista.get(valor).toString());
    }

}
